//go:build ignore

// Regenerates stdlist.go, the standard-library index tilegen uses to
// resolve a package name to an import path.
//
//	go run gen_std.go
//
// It is generated rather than read at runtime because tilegen must work
// where the Go toolchain is not installed: the HTTP service runs in a
// distroless image with no `go` binary, and `go list std` there fails
// silently, leaving every standard package unrecognised.
package main

import (
	"fmt"
	"os"
	"os/exec"
	"sort"
	"strings"
)

func main() {
	out, err := exec.Command("go", "list", "std").Output()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	var paths []string
	for _, p := range strings.Fields(string(out)) {
		if !strings.Contains(p, "internal") && !strings.HasPrefix(p, "vendor/") {
			paths = append(paths, p)
		}
	}
	sort.Strings(paths)
	var b strings.Builder
	b.WriteString("// Code generated by gen_std.go. DO NOT EDIT.\n\npackage main\n\n")
	fmt.Fprintf(&b, "// stdList is the standard library of the Go release tilegen was built\n// with, baked in so tilegen needs no toolchain at runtime.\nvar stdList = []string{\n")
	for _, p := range paths {
		fmt.Fprintf(&b, "\t%q,\n", p)
	}
	b.WriteString("}\n")
	os.WriteFile("stdlist.go", []byte(b.String()), 0o644)
	fmt.Println(len(paths), "packages ->", "stdlist.go")
}
