package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
)

// Spec forms come and go; the code must follow. Reconciliation has one
// rule: tilegen's own files follow the spec exactly, and your files are
// only ever added to.
//
//   - A generated file (header "Code generated by tilegen") that the spec
//     no longer produces is deleted.
//   - A method the spec now requires but your file lacks is appended as a
//     stub with a hole.
//   - An untouched stub (its body is still just the hole) is still pure
//     scaffolding, so it follows the spec: its signature is updated, or it
//     is removed when the spec drops it.
//   - A method you implemented whose signature no longer matches the spec
//     is reported as drift and becomes an LLM task. It is not rewritten.
//   - A method you implemented, or a whole scaffolded file, that the spec no
//     longer produces is reported as an orphan and left in place.
//
// There is no state file: the markers in the files on disk are the state.

const (
	generatedMarker = "Code generated by tilegen. DO NOT EDIT."
	scaffoldMarker  = "Scaffolded by tilegen."
	sqlcMarker      = "Code generated by sqlc. DO NOT EDIT."
)

// Note is one reconciliation finding, reported on the console and in
// tilegen.tasks.json.
type Note struct {
	Kind   string `json:"kind"` // orphan | drift
	File   string `json:"file"`
	Symbol string `json:"symbol,omitempty"`
	Detail string `json:"detail"`
	id     string // hole id, for drift
	line   int
}

// reconcileKeep brings an existing scaffolded file in line with the
// (go/file ...) that would have created it.
func reconcileKeep(n *Node, full, rel string, r *Report) error {
	src, err := os.ReadFile(full)
	if err != nil {
		return err
	}
	fset := token.NewFileSet()
	af, err := parser.ParseFile(fset, full, src, parser.ParseComments)
	if err != nil {
		r.Notes = append(r.Notes, Note{Kind: "orphan", File: rel, Detail: "cannot parse, so it was not reconciled: " + err.Error()})
		r.Kept = append(r.Kept, rel)
		return nil
	}
	have := map[string]*ast.FuncDecl{} // "Type.Method" -> declaration
	for _, d := range af.Decls {
		if fd, ok := d.(*ast.FuncDecl); ok && fd.Recv != nil && len(fd.Recv.List) == 1 {
			have[recvType(fd.Recv.List[0].Type)+"."+fd.Name.Name] = fd
		}
	}

	pkg := n.Text("package")
	want := map[string]bool{}
	managed := map[string]bool{} // receiver types this file's tile manages
	type edit struct {
		start, end int
		text       string
	}
	var edits []edit
	var missing []*Node
	for _, d := range n.FindAll("go/func") {
		rv := d.Find("recv")
		if rv == nil {
			continue // constructors are yours once written
		}
		typ := strings.TrimPrefix(rv.List[2].Atom, "*")
		key := typ + "." + d.List[1].Atom
		want[key], managed[typ] = true, true
		fd, ok := have[key]
		if !ok {
			missing = append(missing, d)
			continue
		}
		got, wantSig := funcType(fset, fd.Type), expectedFuncType(d)
		switch {
		case got == wantSig:
		case untouchedStub(fd):
			start, end := fset.Position(fd.Pos()).Offset, fset.Position(fd.End()).Offset
			edits = append(edits, edit{start, end, strings.TrimRight(renderFunc(d), "\n")})
			r.Restubbed = append(r.Restubbed, fmt.Sprintf("%s in %s", d.List[1].Atom, rel))
		default:
			r.Notes = append(r.Notes, Note{
				Kind: "drift", File: rel, Symbol: fmt.Sprintf("(%s).%s", rv.List[2].Atom, d.List[1].Atom),
				Detail: fmt.Sprintf("has %s; the spec now wants %s", got, wantSig),
				id:     pkg + "." + key, line: fset.Position(fd.Pos()).Line,
			})
		}
	}
	keys := make([]string, 0, len(have))
	for k := range have {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, key := range keys {
		typ, method, _ := strings.Cut(key, ".")
		if !managed[typ] || want[key] {
			continue
		}
		fd := have[key]
		if untouchedStub(fd) {
			start := fd.Pos()
			if fd.Doc != nil {
				start = fd.Doc.Pos()
			}
			edits = append(edits, edit{fset.Position(start).Offset, fset.Position(fd.End()).Offset, ""})
			r.Dropped = append(r.Dropped, fmt.Sprintf("%s from %s", method, rel))
			continue
		}
		r.Notes = append(r.Notes, Note{Kind: "orphan", File: rel, Symbol: fmt.Sprintf("(*%s).%s", typ, method),
			Detail: "you implemented it, but it is no longer in the spec; delete it if nothing uses it"})
	}
	if len(missing) == 0 && len(edits) == 0 {
		r.Kept = append(r.Kept, rel)
		return nil
	}

	// Apply edits back to front so earlier offsets stay valid, append the
	// missing methods, then let the normal Go pipeline fix imports.
	sort.Slice(edits, func(i, j int) bool { return edits[i].start > edits[j].start })
	for _, e := range edits {
		src = append(src[:e.start:e.start], append([]byte(e.text), src[e.end:]...)...)
	}
	var b strings.Builder
	b.Write(bytes.TrimRight(src, "\n"))
	b.WriteString("\n")
	for _, d := range missing {
		d = L(append([]*Node{d.List[0], d.List[1],
			L(Sym("doc"), Str(d.List[1].Atom+" is new in the spec; tilegen appended this stub."))}, d.List[2:]...)...)
		b.WriteString("\n" + renderFunc(d))
		r.Added = append(r.Added, fmt.Sprintf("%s to %s", d.List[1].Atom, rel))
	}
	final, err := finishGo(n, full, rel, b.String())
	if err != nil {
		return fmt.Errorf("reconciling %s: %w", rel, err)
	}
	r.Produced[rel] = true
	r.Updated = append(r.Updated, rel)
	return os.WriteFile(full, final, 0o644)
}

// untouchedStub reports whether a method's body is still exactly the
// tilegen hole, i.e. contains nothing you wrote.
func untouchedStub(fd *ast.FuncDecl) bool {
	if fd.Body == nil || len(fd.Body.List) != 1 {
		return false
	}
	es, ok := fd.Body.List[0].(*ast.ExprStmt)
	if !ok {
		return false
	}
	call, ok := es.X.(*ast.CallExpr)
	if !ok || len(call.Args) != 1 {
		return false
	}
	if id, ok := call.Fun.(*ast.Ident); !ok || id.Name != "panic" {
		return false
	}
	lit, ok := call.Args[0].(*ast.BasicLit)
	return ok && lit.Kind == token.STRING && strings.HasPrefix(strings.Trim(lit.Value, "\"`"), holePrefix)
}

func recvType(e ast.Expr) string {
	switch t := e.(type) {
	case *ast.StarExpr:
		return recvType(t.X)
	case *ast.Ident:
		return t.Name
	case *ast.IndexExpr:
		return recvType(t.X)
	case *ast.IndexListExpr:
		return recvType(t.X)
	}
	return ""
}

// funcType prints a signature's types only, so renamed parameters are not
// drift: func(context.Context, int64) (*Note, error).
func funcType(fset *token.FileSet, ft *ast.FuncType) string {
	list := func(fl *ast.FieldList) []string {
		var out []string
		if fl == nil {
			return out
		}
		for _, f := range fl.List {
			var buf bytes.Buffer
			printer.Fprint(&buf, fset, f.Type)
			for i := 0; i < max(1, len(f.Names)); i++ {
				out = append(out, buf.String())
			}
		}
		return out
	}
	s := "func(" + strings.Join(list(ft.Params), ", ") + ")"
	switch res := list(ft.Results); len(res) {
	case 0:
	case 1:
		s += " " + res[0]
	default:
		s += " (" + strings.Join(res, ", ") + ")"
	}
	return s
}

func expectedFuncType(d *Node) string {
	src := "package p\nfunc " + signature(d) + " {}\n"
	fset := token.NewFileSet()
	af, err := parser.ParseFile(fset, "", src, 0)
	if err != nil {
		return "(" + err.Error() + ")"
	}
	return funcType(fset, af.Decls[0].(*ast.FuncDecl).Type)
}

// sweep deletes tilegen-generated files the spec no longer produces, and
// scaffolded files that are still pure scaffolding. Scaffolded files with
// your code in them are reported as orphans. It walks the output folder,
// skipping hidden folders, vendor, node_modules and nested modules (any
// folder with its own go.mod, such as another tilegen project).
func sweep(out string, r *Report) {
	var generated, scaffolded []string
	sqlcOrphans := map[string]bool{}
	filepath.WalkDir(out, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			if p != out && (strings.HasPrefix(d.Name(), ".") || d.Name() == "vendor" || d.Name() == "node_modules") {
				return filepath.SkipDir
			}
			if _, err := os.Stat(filepath.Join(p, "go.mod")); err == nil && p != out {
				return filepath.SkipDir // another module, maybe another tilegen project: not ours
			}
			return nil
		}
		switch filepath.Ext(p) {
		case ".go", ".sql", ".yaml":
		default:
			return nil
		}
		rel, _ := filepath.Rel(out, p)
		rel = filepath.ToSlash(rel)
		if r.Produced[rel] {
			return nil
		}
		head := make([]byte, 256)
		f, err := os.Open(p)
		if err != nil {
			return nil
		}
		n, _ := f.Read(head)
		f.Close()
		switch h := string(head[:n]); {
		case strings.Contains(h, generatedMarker):
			generated = append(generated, rel)
		case strings.Contains(h, scaffoldMarker):
			scaffolded = append(scaffolded, rel)
		case strings.Contains(h, sqlcMarker) && !r.Produced["sqlc.yaml"]:
			sqlcOrphans[filepath.ToSlash(filepath.Dir(rel))] = true
		}
		return nil
	})
	remove := func(rel string) bool {
		p := filepath.Join(out, filepath.FromSlash(rel))
		if os.Remove(p) != nil {
			return false
		}
		removeEmptyDirs(filepath.Dir(p), out)
		return true
	}
	for _, rel := range generated {
		if remove(rel) {
			r.Removed = append(r.Removed, rel)
		}
	}
	for _, rel := range scaffolded {
		if pureScaffolding(filepath.Join(out, filepath.FromSlash(rel))) {
			if remove(rel) {
				r.RemovedScaffold = append(r.RemovedScaffold, rel)
			}
			continue
		}
		detail := "you implemented code here, but the spec no longer produces this file; delete it, or keep it (say, as a test fake)"
		if !packageProduced(r, path.Dir(rel)) {
			detail = "its package is no longer in the spec, so this file will not compile; move the code you need, then delete it"
		}
		r.Notes = append(r.Notes, Note{Kind: "orphan", File: rel, Detail: detail})
	}
	for _, dir := range sortedKeys(sqlcOrphans) {
		r.Notes = append(r.Notes, Note{Kind: "orphan", File: dir + "/",
			Detail: "sqlc output, but tilegen no longer writes sqlc.yaml; delete the folder if nothing imports it"})
	}
}

// packageProduced reports whether this run still produces a file in dir.
func packageProduced(r *Report, dir string) bool {
	for rel := range r.Produced {
		if path.Dir(rel) == dir {
			return true
		}
	}
	return false
}

// pureScaffolding reports whether a scaffolded file still holds nothing you
// wrote: one struct, its New constructor, and methods that are all
// untouched stubs.
func pureScaffolding(file string) bool {
	fset := token.NewFileSet()
	af, err := parser.ParseFile(fset, file, nil, 0)
	if err != nil {
		return false
	}
	types, ctors := 0, 0
	for _, d := range af.Decls {
		switch d := d.(type) {
		case *ast.GenDecl:
			switch d.Tok {
			case token.TYPE:
				types += len(d.Specs)
			case token.IMPORT:
			default:
				return false // vars or consts you added
			}
		case *ast.FuncDecl:
			switch {
			case d.Recv != nil:
				if !untouchedStub(d) {
					return false
				}
			case strings.HasPrefix(d.Name.Name, "New"):
				ctors++
			default:
				return false // a helper you added
			}
		}
	}
	return types == 1 && ctors <= 1
}

func removeEmptyDirs(dir, stop string) {
	for dir != stop && strings.HasPrefix(dir, stop) {
		if os.Remove(dir) != nil { // fails unless empty
			return
		}
		dir = filepath.Dir(dir)
	}
}
